### ISSUE TITLE
No point cloud of ground plane

### ISSUE THREAD

**Issue by PotatoMa0119** [arshadlab/gazebo_map_creator#4]
Hi,

Thanks for your great work and effort! I built a simple Gazebo world, and the conversion to .pcd file was smooth. However, I found that there's no point cloud for the ground plane, which is necessary for my use case. Could you please let me know if there's any way to include ground plane into the conversion as well?

Thanks in advance!
![WX20240401-121337@2x](https://github.com/arshadlab/gazebo_map_creator/assets/40928075/6a0306e1-aa34-41e5-bb99-31a7522b93c0)
![WX20240401-121409@2x](https://github.com/arshadlab/gazebo_map_creator/assets/40928075/5b19b6bc-4126-48a9-893b-39e495997fbc)

**Comment by arshadlab** [comment]
Hi, 
  The ground plane is likely not included in your case since the lower z coordinates may not be covering it.
  
   # ros2 run gazebo_map_creator request_map.py -c '(-4.8,-4.5,0.03)(4.8,4.5,8.0)' -r 0.01 -f $PWD/map
   
   Change 0.03 to even lower value until you start seeing ground plane being rendered.  Also make sure that ground plane is solid and it's existence can block rays.  Alternatively increasing -r value can also help but results will not be very accurate.
   
Regards,
Arshad

**Comment by PotatoMa0119** [comment]
I adjusted the 0.03 and now I get the ground. Great thanks!
